name: build

on:
  push:
  pull_request:

jobs:
  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pacman -Syu --noconfirm --needed base-devel hyprland
      - name: Build
        run: make
      - name: Test
        run: make test
